#dubbo.application.name=springboot-provider-annotation
#dubbo.registry.protocol=zookeeper
#dubbo.registry.address=192.168.64.128:2181
#dubbo.protocol.port=20884


dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.64.128:2181
  protocol:
    port: 20881






spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v16?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: hBt6fsAqC3zzWsqUAs11oxqtZGdwNXg5pFr1SYeT0IDhCO5lCdJt1S0yxa9wAeJ9lSO00AqTu0a9ZVG0OD2llw==
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALIyjpsJf4n6dzqRMSPFbbCOhDElRocNfz2xLXzHTG2Xb0TDkTPu1vZ5nH7mA9pKPzlkJlSOA8QWUZlXhTgUyLcCAwEAAQ==

server:
  port: 8080
